parameters:
    nova_ezseo.default.robots_disallow: []
    nova_ezseo.default.robots:
        sitemap:
#            - { route : '_novaseo_sitemap_index' }
#            - { url : 'https://www.google.fr/sitemap.xml' }
        allow: []
        disallow: []
    nova_ezseo.default.google_gatracker: ~
    nova_ezseo.default.google_verification: 1234567890
    nova_ezseo.default.google_anonymizeIp: ~
    nova_ezseo.default.bing_verification: ~
    nova_ezseo.default.custom_fallback_service: ~
    nova_ezseo.default.limit_to_rootlocation: ~
    nova_ezseo.default.sitemap_excludes:
        locations: []
        subtrees: []
        contentTypeIdentifiers: ['image']
    nova_ezseo.default.default_metas:
        author: "eZ Community Bundle Nova eZ SEO Bundle"
        copyright: ~
        generator: "eZ Platform"
        MSSmartTagsPreventParsing: "TRUE"
    nova_ezseo.default.default_links:
        Index:
            href: { location_id: 2 }
            title: 'Home'
#        Top:
#            href: { route : 'route_name' }
#            title: 'Home'
#        Search:
#            href: { route: 'search_route_name' }
#            title: 'Search'
        'Shortcut icon':
            href: { asset: { path: '/bundles/sitebundle/images/favicon.ico' } }
            type: 'image/x-icon'
#        Alternate:
#            href: { route: 'rss_feed_route_name' }
#            title: 'RSS'
#            type: 'application/rss+xml'
    nova_ezseo.default.fieldtype_metas_identifier: "metas"
    nova_ezseo.default.fieldtype_metas:
        title:
            label: 'Title'
            default_pattern: "<title|name>"
            params:
                label: false
                empty_data: ''
            icon: 'book'
        description:
            label: 'Description'
            params:
                label: false
                empty_data: ''
            default_pattern: ~
            icon: 'book'
        keywords:
            label: 'Keywords'
            default_pattern: ~
            icon: 'tags'
        'canonical':
            label: 'External Canonical URL'
            params:
                label: false
                empty_data: ''
            default_pattern: ~
            icon: 'link'
        'og:title':
            label: 'Facebook - Title'
            params:
                label: false
                empty_data: ''
            default_pattern: "<title|name>"
            icon: 'facebook-official'
        'og:description':
            label: 'Facebook - Description'
            params:
                label: false
                empty_data: ''
            default_pattern: "<short_description|description|title|name>"
            icon: 'facebook-official'
        'og:image':
            label: 'Facebook - Image'
            params:
                label: false
                empty_data: ''
            default_pattern: "<image|picture>"
            icon: 'facebook-official'
        'twitter:title':
            label: 'Twitter - Title'
            params:
                label: false
                empty_data: ''
            default_pattern: "<title|name>"
            icon: 'twitter-square'
        'twitter:description':
            label: 'Twitter - Description'
            params:
                label: false
                empty_data: ''
            default_pattern: "<short_description|description|title|name>"
            icon: 'twitter-square'
        'twitter:image':
            label: 'Twitter - Image'
            params:
                label: false
                empty_data: ''
            default_pattern: "<image|picture>"
            icon: 'twitter-square'
        'robots':
            label: 'Robots'
            type: 'boolean'
            params:
                label: 'NOINDEX'
                attr:
                    class: form-control
                    false_values: '0'
            default_pattern: 'all'
            icon: 'book'
